
CREATE DATABASE ART_MUSEUM;
USE ART_MUSEUM;

CREATE TABLE ARTIST   
(   
AId CHAR(4) NOT NULL PRIMARY KEY,   
Fname VARCHAR(20) NOT NULL,   
Lname VARCHAR(20) NOT NULL,   
DOB DATE,   
DOD DATE,   
Country VARCHAR(20),   
Epoch VARCHAR(20),   
MStyle VARCHAR(50),   
Description VARCHAR(200) 
);

CREATE TABLE COLLECTIONS   
(   
Cname VARCHAR(50) NOT NULL PRIMARY KEY,   
Ctype VARCHAR(50) NOT NULL,   
Address VARCHAR(100),   
Phone CHAR(10),   
Contact_Person VARCHAR(50),   
Description VARCHAR(200)  
);

CREATE TABLE EXHIBITIONS  
(   
EName VARCHAR(50) NOT NULL PRIMARY KEY, 
SDate DATE NOT NULL, 
EDate DATE NOT NULL 
);

CREATE TABLE ART_OBJECT   
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
AId CHAR(4), 
CYear CHAR(4), 
Title VARCHAR(50),  
Description VARCHAR(200), 
Ename VARCHAR(50), 
FOREIGN KEY (AId) REFERENCES ARTIST(AId) ON UPDATE CASCADE ON DELETE SET NULL,
FOREIGN KEY (Ename) REFERENCES EXHIBITIONS(Ename) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE PAINTING 
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
Paint_type VARCHAR(20),
Drawn_on VARCHAR(20),   
OStyle VARCHAR(20), 
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SCULPTURE
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
Material VARCHAR(20),
Height DECIMAL(10,2),   
Weight DECIMAL(10,2),
OStyle VARCHAR(20),
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OTHER 
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
OType VARCHAR(20),  
OStyle VARCHAR(20), 
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PERMANENT_COLLECTION 
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
Aqd_date DATE NOT NULL,  
Status VARCHAR(20),
OCost DECIMAL(10,2), 
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE BORROWED 
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
CBname VARCHAR(50), 
Bdate DATE NOT NULL, 
Rdate DATE NOT NULL,
CHECK(Bdate < Rdate), 
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (CBname) REFERENCES COLLECTIONS(Cname) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE INFORMATION
(   
ObId CHAR(4) NOT NULL PRIMARY KEY, 
Country VARCHAR(20),
Epoch VARCHAR(20), 
FOREIGN KEY (ObId) REFERENCES ART_OBJECT(ObId) ON UPDATE CASCADE ON DELETE CASCADE
);

