CREATE DATABASE EMP_DEPT;
USE EMP_DEPT;

CREATE TABLE DEPARTMENT(
Dno INT NOT NULL,
Dname VARCHAR(50),
Location VARCHAR(50) DEFAULT 'New Delhi',
PRIMARY KEY(Dno)
);

CREATE TABLE EMPLOYEE(
Eno CHAR(3) NOT NULL,
Ename VARCHAR(50) NOT NULL,
Job_type VARCHAR(50) NOT NULL,
SupervisonEno CHAR(3),
Hire_date DATE NOT NULL,
Dno INT,
Commission DECIMAL(10,2),
Salary DECIMAL(7,2) NOT NULL,
PRIMARY KEY(Eno),
FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dno),
FOREIGN KEY(SupervisonEno) REFERENCES EMPLOYEE(Eno)
);